import { Worker, type JobsOptions } from "bullmq";
import { z } from "zod";
import { connectDB } from "@/lib/db/client";
import { bullConnection, ocrQueue, emailQueue } from "@/lib/workers/queue";
import { extractInvoiceDetailsFromPdfBuffer } from "@/lib/pdfInvoiceExtract";
import Invoice from "@/models/Invoice";
import { sendEmail } from "@/lib/email";
import { log } from "@/lib/monitoring/logger";

const OcrJobSchema = z.object({
  requestId: z.string().min(1),
  tenantId: z.string().min(1),
  sellerId: z.string().min(1),
  buyerId: z.string().min(1),
  sellerName: z.string().min(1),
  sellerEmail: z.string().email(),
  buyerName: z.string().min(1),
  buyerEmail: z.string().email(),
  fileUrl: z.string().url(),
  notifyEmail: z.string().email(),
});

type OcrJobData = z.infer<typeof OcrJobSchema>;

async function fetchFileAsBuffer(fileUrl: string) {
  const response = await fetch(fileUrl);

  if (!response.ok) {
    throw new Error(`Failed to download OCR file: ${response.status} ${response.statusText}`);
  }

  const arr = await response.arrayBuffer();
  return Buffer.from(arr);
}

async function enqueueEmail(to: string, subject: string, html: string) {
  const payload = { to, subject, html };
  const opts: JobsOptions = {
    attempts: 5,
    backoff: {
      type: "exponential",
      delay: 3000,
    },
  };

  await emailQueue.add("ocr-email", payload, opts);
}

async function processOcrJob(data: OcrJobData) {
  const fileBuffer = await fetchFileAsBuffer(data.fileUrl);
  const ocrResult = await extractInvoiceDetailsFromPdfBuffer(fileBuffer);

  const extracted = ocrResult.extracted;
  const issueDate = extracted.issueDate ? new Date(extracted.issueDate) : new Date();
  const dueDate = extracted.dueDate ? new Date(extracted.dueDate) : new Date(Date.now() + 30 * 24 * 60 * 60 * 1000);

  await connectDB();

  const invoice = await Invoice.create({
    companyId: data.tenantId,
    invoiceNumber: extracted.invoiceNumber || `INV-${Date.now()}`,
    sellerId: data.sellerId,
    buyerId: data.buyerId,
    sellerName: data.sellerName,
    sellerEmail: data.sellerEmail,
    buyerName: extracted.buyerName || data.buyerName,
    buyerEmail: extracted.buyerEmail || data.buyerEmail,
    issueDate,
    deliveryDate: issueDate,
    dueDate,
    currency: "INR",
    subtotalAmount: Number(extracted.subtotalAmount || 0),
    taxAmount: Number(extracted.taxAmount || 0),
    totalAmount: Number(extracted.totalAmount || 0),
    lineItems: extracted.lineItems || [],
    notes: "Generated by OCR worker",
    status: "Draft",
    isDeleted: false,
  });

  const subject = `OCR complete for invoice ${invoice.invoiceNumber}`;
  const html = `<p>OCR processing has completed.</p><p>Invoice Number: <b>${invoice.invoiceNumber}</b></p>`;

  try {
    await enqueueEmail(data.notifyEmail, subject, html);
  } catch (error) {
    await sendEmail({ to: data.notifyEmail, subject, html });
    log.warn({ requestId: data.requestId, tenantId: data.tenantId, error }, "Email queue unavailable, sent email directly");
  }

  return {
    invoiceId: String(invoice._id),
    invoiceNumber: invoice.invoiceNumber,
    isInvoiceLike: ocrResult.isInvoiceLike,
  };
}

const worker = new Worker(
  "q.ocr",
  async (job) => {
    const parsed = OcrJobSchema.parse(job.data);

    log.info({ requestId: parsed.requestId, tenantId: parsed.tenantId, jobId: String(job.id) }, "OCR job started");

    const result = await processOcrJob(parsed);

    log.info({ requestId: parsed.requestId, tenantId: parsed.tenantId, jobId: String(job.id), result }, "OCR job completed");

    return result;
  },
  {
    connection: bullConnection,
    concurrency: Number(process.env.WORKER_CONCURRENCY_OCR || 5),
  },
);

worker.on("failed", (job, error) => {
  log.error(
    {
      requestId: String(job?.data?.requestId || "unknown"),
      tenantId: String(job?.data?.tenantId || "unknown"),
      jobId: String(job?.id || "unknown"),
      error,
    },
    "OCR job failed",
  );
});

worker.on("ready", () => {
  log.info({ requestId: "system", tenantId: "system" }, "OCR worker ready");
});

process.on("SIGTERM", async () => {
  await worker.close();
  await ocrQueue.close();
  await emailQueue.close();
  process.exit(0);
});
