import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import Invoice from "@/models/Invoice";
import {
  requireAuth,
  errorResponse,
  ensureCompanyAccess,
} from "@/lib/api/routeUtils";

function drawLine(page, text, x, y, size = 10) {
  page.drawText(String(text || ""), {
    x,
    y,
    size,
    font: page.docFont,
    color: rgb(0.07, 0.1, 0.18),
  });
}

export async function GET(req, { params }) {
  const auth = await requireAuth(req);
  if (!auth.ok) return auth.response;

  const { id } = await params;
  const invoice = await Invoice.findById(id).lean();

  if (!invoice || invoice.isDeleted) {
    return errorResponse("NOT_FOUND", "Invoice not found", 404, auth.requestId);
  }

  if (!ensureCompanyAccess(invoice.companyId, auth.companyId)) {
    return errorResponse("FORBIDDEN", "Invoice does not belong to your company", 403, auth.requestId);
  }

  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const page = pdfDoc.addPage([595, 842]);
  page.docFont = font;

  page.drawRectangle({ x: 0, y: 790, width: 595, height: 52, color: rgb(0.06, 0.11, 0.18) });
  page.drawText("NEXUS THREE", { x: 32, y: 810, size: 14, font: fontBold, color: rgb(1, 1, 1) });
  page.drawText("Tax Invoice", { x: 495, y: 810, size: 12, font: fontBold, color: rgb(1, 1, 1) });

  let y = 760;
  const leftX = 32;
  const rightX = 330;

  page.drawText(`Invoice #: ${invoice.invoiceNumber || "-"}`, { x: leftX, y, size: 11, font: fontBold, color: rgb(0.07, 0.1, 0.18) });
  page.drawText(`Issue Date: ${invoice.issueDate ? new Date(invoice.issueDate).toLocaleDateString("en-IN") : "-"}`, { x: rightX, y, size: 10, font });
  y -= 16;
  page.drawText(`Due Date: ${invoice.dueDate ? new Date(invoice.dueDate).toLocaleDateString("en-IN") : "-"}`, { x: leftX, y, size: 10, font });
  page.drawText(`Currency: ${invoice.currency || "INR"}`, { x: rightX, y, size: 10, font });

  y -= 24;
  page.drawText("Seller", { x: leftX, y, size: 10, font: fontBold });
  page.drawText("Buyer", { x: rightX, y, size: 10, font: fontBold });
  y -= 14;
  drawLine(page, invoice.sellerName || "-", leftX, y);
  drawLine(page, invoice.buyerName || "-", rightX, y);
  y -= 14;
  drawLine(page, `GSTIN: ${invoice.sellerGstin || "-"}`, leftX, y);
  drawLine(page, `GSTIN: ${invoice.buyerGstin || "-"}`, rightX, y);

  y -= 26;
  page.drawRectangle({ x: leftX, y, width: 531, height: 20, color: rgb(0.06, 0.11, 0.18) });
  page.drawText("Description", { x: leftX + 8, y: y + 6, size: 9, font: fontBold, color: rgb(1, 1, 1) });
  page.drawText("Qty", { x: 335, y: y + 6, size: 9, font: fontBold, color: rgb(1, 1, 1) });
  page.drawText("Rate", { x: 390, y: y + 6, size: 9, font: fontBold, color: rgb(1, 1, 1) });
  page.drawText("Total", { x: 490, y: y + 6, size: 9, font: fontBold, color: rgb(1, 1, 1) });

  y -= 16;
  const items = Array.isArray(invoice.lineItems) ? invoice.lineItems : [];
  for (const item of items.slice(0, 15)) {
    drawLine(page, item.description || "-", leftX + 8, y, 9);
    drawLine(page, item.quantity ?? "-", 335, y, 9);
    drawLine(page, item.unitPrice ?? "-", 390, y, 9);
    drawLine(page, item.total ?? "-", 490, y, 9);
    y -= 14;
  }

  y -= 10;
  page.drawText(`Subtotal: INR ${Number(invoice.subtotalAmount || 0).toLocaleString("en-IN")}`, { x: 380, y, size: 10, font });
  y -= 14;
  page.drawText(`Tax: INR ${Number(invoice.taxAmount || 0).toLocaleString("en-IN")}`, { x: 380, y, size: 10, font });
  y -= 14;
  page.drawText(`TDS: INR ${Number(invoice.tdsAmount || 0).toLocaleString("en-IN")}`, { x: 380, y, size: 10, font });
  y -= 16;
  page.drawText(`Grand Total: INR ${Number(invoice.totalAmount || 0).toLocaleString("en-IN")}`, { x: 380, y, size: 11, font: fontBold });

  if (invoice.eInvoiceStatus === "submitted" && invoice.eInvoiceIRN) {
    y -= 28;
    page.drawText("GST IRN", { x: leftX, y, size: 10, font: fontBold });
    y -= 14;
    page.drawText(String(invoice.eInvoiceIRN), { x: leftX, y, size: 8, font });

    if (invoice.eInvoiceQRCode && String(invoice.eInvoiceQRCode).startsWith("data:image")) {
      try {
        const base64 = String(invoice.eInvoiceQRCode).split(",")[1] || "";
        const bytes = Uint8Array.from(Buffer.from(base64, "base64"));
        const png = await pdfDoc.embedPng(bytes);
        page.drawImage(png, { x: 480, y: y - 12, width: 80, height: 80 });
      } catch {
        // ignore invalid QR image payloads
      }
    }
  }

  page.drawText("Generated by Nexus Three | nexusthree.io", { x: 32, y: 24, size: 9, font });

  const bytes = await pdfDoc.save();
  const filename = `INV-${invoice.invoiceNumber || "invoice"}.pdf`;

  return new Response(Buffer.from(bytes), {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename=${filename}`,
      "X-Request-ID": auth.requestId,
    },
  });
}
