import { z } from "zod";
import Invoice from "@/models/Invoice";
import { calculatePenalty, getOverdueDays, getMsmedDeadline } from "@/lib/complianceCalc";
import { requireAuth, parseBody, successResponse, errorResponse } from "@/lib/api/routeUtils";

const SamadhaanSchema = z.object({
  invoiceId: z.string().min(1),
});

export async function POST(req) {
  const auth = await requireAuth(req);
  if (!auth.ok) return auth.response;
  if (auth.user.userType !== "Seller") {
    return errorResponse(
      "FORBIDDEN",
      "Only MSME sellers can generate Samadhaan documents",
      403,
      auth.requestId,
    );
  }

  const parsed = await parseBody(req, SamadhaanSchema, auth.requestId);
  if (!parsed.ok) return parsed.response;

  const { invoiceId } = parsed.data;
  const invoice = await Invoice.findById(invoiceId).lean();
  if (!invoice) return errorResponse("NOT_FOUND", "Invoice not found", 404, auth.requestId);

  const deadline = invoice.msmedDeadline
    ? new Date(invoice.msmedDeadline)
    : getMsmedDeadline(invoice.issueDate, invoice.paymentTermsDays || 45);
  const overdueDays = getOverdueDays(deadline);
  if (overdueDays <= 0) {
    return errorResponse(
      "INVALID_STATE",
      "Invoice is not overdue - Samadhaan escalation not applicable",
      400,
      auth.requestId,
    );
  }

  const rbiRate = parseFloat(process.env.RBI_BANK_RATE || "0.065");
  const penalty = calculatePenalty(invoice.totalAmount, overdueDays, rbiRate);

  const fmt = (d) => new Date(d).toLocaleDateString("en-IN");

  const documentText = `
=====================================================
              MSME SAMADHAAN - FORM 1
       Application for Delayed Payment Under
  MSMED Act, 2006 (Section 15 read with Section 18)
=====================================================

SECTION A: APPLICANT (MSME SUPPLIER) DETAILS
---------------------------------------------
Name of Enterprise:     ${invoice.sellerName}
Email:                  ${invoice.sellerEmail}
GSTIN:                  ${invoice.sellerGstin || "Not on file"}

SECTION B: RESPONDENT (BUYER) DETAILS
---------------------------------------------
Name of Buyer:          ${invoice.buyerName}
Email:                  ${invoice.buyerEmail}
GSTIN:                  ${invoice.buyerGstin || "Not on file"}

SECTION C: INVOICE & PAYMENT DETAILS
---------------------------------------------
Invoice Number:         ${invoice.invoiceNumber}
Invoice Date:           ${fmt(invoice.issueDate)}
Invoice Amount:         INR ${invoice.totalAmount.toLocaleString("en-IN")}
Payment Terms:          ${invoice.paymentTermsDays} days
Due Date:               ${fmt(invoice.dueDate)}
MSMED Deadline:         ${fmt(deadline)}
Days Overdue:           ${overdueDays} days
Invoice Status:         ${invoice.status}

SECTION D: PENALTY INTEREST CALCULATION
---------------------------------------------
RBI Bank Rate:          ${penalty.rbiBaseRate}
Applied Rate (3x):      ${penalty.appliedRateAnnual}
Method:                 Compound interest, monthly rests
Principal Amount:       INR ${penalty.principal.toLocaleString("en-IN")}
Interest Accrued:       INR ${penalty.interest.toLocaleString("en-IN")}
Total Payable:          INR ${penalty.totalPayable.toLocaleString("en-IN")}

SECTION E: PRAYER / RELIEF SOUGHT
---------------------------------------------
The applicant respectfully requests the Hon'ble Micro and
Small Enterprise Facilitation Council to:

1. Direct the Respondent to make immediate payment of the
   outstanding principal amount of INR ${penalty.principal.toLocaleString("en-IN")}.
2. Direct the Respondent to pay compound interest of
   INR ${penalty.interest.toLocaleString("en-IN")} as per Section 16 of the MSMED Act, 2006.
3. Award costs of the present proceedings.

SECTION F: TIMELINE OF EVENTS
---------------------------------------------
${fmt(invoice.issueDate)}    Invoice issued
${fmt(invoice.deliveryDate)} Goods/Services delivered
${fmt(deadline)}             MSMED payment deadline passed
${fmt(new Date())}           Samadhaan application generated (${overdueDays} days overdue)

=====================================================
      Generated by Nexus Three
      Date: ${fmt(new Date())}
=====================================================
`.trim();

  return successResponse(
    {
      documentText,
      filename: `Samadhaan_Form1_${invoice.invoiceNumber}_${Date.now()}.txt`,
      invoiceNumber: invoice.invoiceNumber,
      overdueDays,
      penalty,
    },
    200,
    auth.requestId,
  );
}
